### ISSUE TITLE
Windows build is broken out of the box

### ISSUE THREAD

**Issue by papeh** [sillsdev/icu-dotnet#160]
## Describe the bug

Building the project using the instructions in README.md fails on a fresh clone on Windows using Visual Studio 2019

## To Reproduce

* Clone the project
* Open `x64_x86 Cross Tools Command Prompt for VS 2019` and `cd` to the repository root
* Run `msbuild /t:Test build/icu-dotnet.proj`
Expected: project builds and tests pass
Actual: build fails with
```
"C:\fwrepo\icu-dotnet\build\icu-dotnet.proj" (Test target) (1) ->
"C:\fwrepo\icu-dotnet\source\icu.net.sln" (Rebuild target) (3) ->
(ValidateSolutionConfiguration target) ->
  C:\fwrepo\icu-dotnet\source\icu.net.sln.metaproj : error MSB4126: The specified solution configuration "Release|x86"
is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild
.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solu
tion configuration. [C:\fwrepo\icu-dotnet\source\icu.net.sln]
```

**Comment by ermshiperete** [comment]
It works with the "x64 Native Tools Command Prompt for VS 2019".

**Comment by ermshiperete** [comment]
#161 contains a fix that makes the instructions from the `README.md` work again :smiley:

**Comment by papeh** [comment]
Solved now that we're building with `dotnet`
