### ISSUE TITLE
Icu library not compatible with alpine 3.16

### ISSUE THREAD

**Issue by santoshsg1308** [sillsdev/icu-dotnet#167]
We are using below icu nuget packages
![image](https://user-images.githubusercontent.com/86598581/175307801-2d4fc186-2ac2-462b-b658-b74b93d82eed.png)

And below is the code  
```
 using (var transliteratorLatn = Icu.Transliterator.CreateInstance("Any-Latn"))
                {
                    return transliteratorLatn.Transliterate(input, textMultiplier);
                }
```
Everything was working fine with alpine3.15 and icu=69.1-r1. However moving to alpine3.16 and icu=71.1-r2 the above code started to give the below exception
![image](https://user-images.githubusercontent.com/86598581/175308448-d2add4d9-b331-43c1-8f4e-2ec8beb811f5.png)

Did already raised a bug report at  https://github.com/dotnet/dotnet-docker/issues/3851 to fix the error in the build pipeline.

However, for the exception occuring in the code it was advised the icu.net repo is not compatible with alpine3.16. Can you please help?

**Comment by ermshiperete** [comment]
This will be fixed in 2.8.0.
