### ISSUE TITLE
DllResolver fails with Ubuntu 22.04 (no libdl.so)

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/icu-dotnet#181]
## Describe the bug

Upon updating The Combine from 20.04 to 22.04, our backend encounters the following: `System.DllNotFoundException : Unable to load shared library 'libdl.so' or one of its dependencies`. This appears to be from the configuration in https://github.com/sillsdev/icu-dotnet/blob/master/source/icu.net/App.config that is enforced by https://github.com/sillsdev/icu-dotnet/blob/master/source/icu.net/NativeMethods/DllResolver.cs.

The error is further documented in https://github.com/sillsdev/TheCombine/issues/1768

## Environment

- Ubuntu 22.04
- icu.net 2.7.1 & 2.8.1

**Comment by papeh** [comment]
Even when copying `icu.net.dll.config` and including its content in `SIL.LCModel.Core.Tests/App.config`, tests fail with
```
   System.DllNotFoundException : libdl.so assembly:<unknown assembly> type:<unknown type> member:(null)
  Stack Trace:
    at (wrapper managed-to-native) SIL.LCModel.Core.SpellChecking.SpellEngineLinux.dlopen(string,int)
  at SIL.LCModel.Core.SpellChecking.SpellEngineLinux.get_Library () [0x00014] in <8dfbb8a640e7481f8301a9226f75cf3f>:0 
  at SIL.LCModel.Core.SpellChecking.SpellEngineLinux.Hunspell_initialize (System.Byte[] affFile, System.Byte[] dictFile) [0x00000] in <8dfbb8a640e7481f8301a9226f75cf3f>:0 
```
Anything else I need to do?

**Comment by ermshiperete** [comment]
That's a rabbit trail. Note that this reference of `libdl.so` doesn't come from `icu.net` code but instead from `SIL.LCModel.Core` which is missing a dll mapping for `libdl.so`. So this is not a bug in `icu.net`.

See https://github.com/sillsdev/liblcm/pull/267#discussion_r1048647448
