### ISSUE TITLE
Build warning on .NET 8

### ISSUE THREAD

**Issue by DmitryMak** [sillsdev/icu-dotnet#193]
## Describe the bug

Build warnings after adding Icu4c.Win.Min

`:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win7-x64, win7-x86. Affected libraries: Icu4c.Win.Min. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.`

.csproj contains
```
<PackageReference Include="icu.net" />
<PackageReference Include="Icu4c.Win.Min" />
```

## To Reproduce

Install Icu4c.Win.Min on a .NET 8 project

## Expected behavior

No warnings

**Comment by ermshiperete** [comment]
Fixed in Icu4c.Win.Min (and Icu4c.Win.Full.*) version 62.2.3
