### ISSUE TITLE
Support of regular expressions

### ISSUE THREAD

**Issue by murata0204** [sillsdev/icu-dotnet#32]
Since ICU provides a very good support of Unicode regular expressions, it would be nice if icu-dotnet supports them.

I did an experimental implementation in [my fork](https://github.com/murata0204/icu-dotnet/tree/regexp).  It only supports a few functions.  How do people feel?

**Comment by ermshiperete** [comment]
I'd be happy to include this. Please create a pull request.

**Comment by murata0204** [comment]
Done.
