### ISSUE TITLE
Mark icu-dotnet CLSCompliant(true)

### ISSUE THREAD

**Issue by NightOwl888** [sillsdev/icu-dotnet#33]
Since the assembly is not marked CLS compliant, it is not possible to consume icu-dotnet and expose any of its types publicly in a CLS compliant assembly. Not marking with `[assembly: CLSCompliant(true)]` means *all* types in the library are not CLS compliant, including interfaces and enumerations.

It would be helpful for consumers of this class who are CLS compliant if icu-dotnet were also CLS compliant (even if some of its types need to be marked CLSCompliant(false) to meet this requirement).

**Comment by ermshiperete** [comment]
Thanks for reporting this! This will be included in version 2.1.1.
