### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by kerbooo** [sillsdev/icu-dotnet#63]
I am C# developer and I would like to Hebrew, Krill or Pinyin chart to latin chars. How can I do that? is there any tutorials?

**Comment by ermshiperete** [comment]
icu-dotnet is a wrapper around ICU4C, so check out the [documentation for ICU4C](http://icu-project.org/apiref/icu4c/). If you have an idea how to do it in ICU4C you hopefully will find the wrapped methods in icu-dotnet. Also, I added a small usage section to the readme with a simple sample.
