### ISSUE TITLE
v2.3.3 throws System.BadImageFormatException

### ISSUE THREAD

**Issue by funex** [sillsdev/icu-dotnet#70]
Hi,

I've just updated from 2.3.2 to 2.3.3 and I get the following exception:

System.BadImageFormatException : Could not load file or assembly 'icu.net, Version=2.3.3.0, Culture=neutral, PublicKeyToken=416fdd914afa6b66' or one of its dependencies. An attempt was made to load a program with an incorrect format.

For IIS to work with icu.net I need let the app pool allow 32 bit applications.
My test solution's platform is set to "ANY CPU" but fails to load icu.net as well.

Any changes from 2.3.2 ?

**Comment by ermshiperete** [comment]
Thanks for reporting this problem!

Somehow the wrong target platform sneaked in when I switched to the new csproj format.

**Comment by ermshiperete** [comment]
This will be fixed in 2.4.0

**Comment by ermshiperete** [comment]
Also fixed in 2.3.4

**Comment by funex** [comment]
Cheers!
